Repository Team-Ilmansa/yeogiga-was, pull requests merged in 2025-07, with the labels that each got.

#88 Fix: 사용자 프로필 이미지 업로드 과정 중 삭제 처리 오류 해결
  src/main/java/kr/co/yeogiga/application/image/service/ImageProcessingService.java
Labels: fix

#89 Feature(IL-187): 이메일 인증 번호 발송 및 검증
  build.gradle
  src/main/java/kr/co/yeogiga/application/auth/dto/VerificationCodeDto.java
  src/main/java/kr/co/yeogiga/application/auth/service/VerificationCodeService.java
  src/main/java/kr/co/yeogiga/common/util/VerificationCodeGenerator.java
  src/main/java/kr/co/yeogiga/domain/auth/exception/AuthErrorType.java
  src/main/java/kr/co/yeogiga/domain/auth/repository/VerificationCodeCache.java
  src/main/java/kr/co/yeogiga/domain/auth/repository/VerificationCodeRepository.java
  src/main/java/kr/co/yeogiga/infrastructure/mail/EmailSender.java
  src/main/java/kr/co/yeogiga/infrastructure/mail/JavaEmailSender.java
  src/main/java/kr/co/yeogiga/infrastructure/mail/VerificationCodeEmailSender.java
  src/main/java/kr/co/yeogiga/infrastructure/mail/constant/MailConstant.java
  src/main/java/kr/co/yeogiga/infrastructure/redis/RedisRepository.java
  src/main/java/kr/co/yeogiga/presentation/auth/api/VerificationApi.java
  src/main/java/kr/co/yeogiga/presentation/auth/controller/VerificationController.java
  src/main/resources/application.yml
  src/test/java/kr/co/yeogiga/application/auth/service/VerificationCodeGeneratorTest.java
  src/test/java/kr/co/yeogiga/application/auth/service/VerificationCodeServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/auth/controller/VerificationControllerTest.java
Labels: feat, chore

#90 Chore: 다음 스마트워크 이메일 사용으로 인한 smtp 플랫폼 변경
  src/main/resources/application.yml
Labels: chore

#92 Refactor: 목적지 카테고리 설정 변경
  src/main/java/kr/co/yeogiga/application/tripplace/dto/TripDaySummaryRes.java
  src/main/java/kr/co/yeogiga/application/tripplace/dto/TripPlaceReq.java
  src/main/java/kr/co/yeogiga/application/tripplace/dto/TripPlaceRes.java
  src/main/java/kr/co/yeogiga/application/tripplace/image/dto/TripPlaceImageRes.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceCommandService.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceEditingService.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceSortService.java
  src/main/java/kr/co/yeogiga/domain/tripplace/entity/Place.java
  src/main/java/kr/co/yeogiga/domain/tripplace/type/PlaceCategory.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/api/TripPlaceApi.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/controller/TripPlaceController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripQueryServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageAssignmentServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageMovementServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageQueryServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceCommandServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceEditingServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceQueryServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceSavingServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceSortServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripControllerTest.java
  src/test/java/kr/co/yeogiga/presentation/tripplace/controller/TripPlaceControllerTest.java
  src/test/java/kr/co/yeogiga/presentation/tripplace/controller/TripPlaceEditingControllerTest.java
Labels: refact

#94 Feature(IL-102): OAuth 로그인 웹-모바일 환경 분리
  src/main/java/kr/co/yeogiga/application/auth/dto/SignInDto.java
  src/main/java/kr/co/yeogiga/application/auth/service/OAuthManagementService.java
  src/main/java/kr/co/yeogiga/presentation/auth/api/OAuthApi.java
  src/main/java/kr/co/yeogiga/presentation/auth/controller/OAuthController.java
  src/test/java/kr/co/yeogiga/presentation/oauth/controller/OAuthControllerTest.java
Labels: feat

#95 Feature(IL-214): 전체 공지사항 조회 기능 구현
  src/main/java/kr/co/yeogiga/application/notice/service/NoticeQueryService.java
  src/main/java/kr/co/yeogiga/domain/notice/dto/NoticeDto.java
  src/main/java/kr/co/yeogiga/domain/notice/repository/CustomNoticeRepository.java
  src/main/java/kr/co/yeogiga/domain/notice/repository/CustomNoticeRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/notice/repository/NoticeRepository.java
  src/main/java/kr/co/yeogiga/domain/notice/service/NoticeService.java
  src/main/java/kr/co/yeogiga/infrastructure/config/PageConfig.java
  src/main/java/kr/co/yeogiga/presentation/auth/api/OAuthApi.java
  src/main/java/kr/co/yeogiga/presentation/auth/controller/OAuthController.java
  src/main/java/kr/co/yeogiga/presentation/calendar/api/CalendarApi.java
  src/main/java/kr/co/yeogiga/presentation/calendar/controller/CalendarController.java
  src/main/java/kr/co/yeogiga/presentation/notice/api/NoticeApi.java
  src/main/java/kr/co/yeogiga/presentation/notice/controller/NoticeController.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripMemberApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripController.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripMemberController.java
  src/main/java/kr/co/yeogiga/presentation/user/api/UserApi.java
  src/main/java/kr/co/yeogiga/presentation/user/controller/UserController.java
  src/test/java/kr/co/yeogiga/application/notice/service/NoticeQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/notice/controller/NoticeControllerTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripControllerTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripMemberControllerTest.java
Labels: feat

#96 Refactor: Trip 엔티티 DTO 생성
  src/main/java/kr/co/yeogiga/application/trip/dto/TripRes.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripQueryService.java
  src/main/java/kr/co/yeogiga/domain/trip/dto/TripDto.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/CustomTripMemberRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/CustomTripMemberRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripMemberService.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripControllerTest.java
Labels: refact

#97 Feature(IL-220): 공지사항 수정 기능 구현
  src/main/java/kr/co/yeogiga/application/notice/service/NoticeCommandService.java
  src/main/java/kr/co/yeogiga/domain/notice/entity/Notice.java
  src/main/java/kr/co/yeogiga/domain/notice/exception/NoticeErrorType.java
  src/main/java/kr/co/yeogiga/domain/notice/repository/CustomNoticeRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/notice/service/NoticeService.java
  src/main/java/kr/co/yeogiga/presentation/notice/api/NoticeApi.java
  src/main/java/kr/co/yeogiga/presentation/notice/controller/NoticeController.java
  src/test/java/kr/co/yeogiga/application/notice/service/NoticeCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/notice/controller/NoticeControllerTest.java
Labels: feat
