Repository Team-Ilmansa/yeogiga-was, pull requests merged in 2025-05, with the labels that each got.

#21 Feat(IL-49): 일반 로그인 및 회원가입
  src/main/java/kr/co/yeogiga/application/auth/dto/SignInDto.java
  src/main/java/kr/co/yeogiga/application/auth/dto/SignUpDto.java
  src/main/java/kr/co/yeogiga/application/auth/service/AuthService.java
  src/main/java/kr/co/yeogiga/application/auth/service/JwtService.java
  src/main/java/kr/co/yeogiga/application/auth/service/OAuthManagementService.java
  src/main/java/kr/co/yeogiga/domain/auth/exception/AuthErrorType.java
  src/main/java/kr/co/yeogiga/domain/user/entity/User.java
  src/main/java/kr/co/yeogiga/domain/user/exception/UserErrorType.java
  src/main/java/kr/co/yeogiga/domain/user/repository/UserRepository.java
  src/main/java/kr/co/yeogiga/domain/user/service/UserService.java
  src/main/java/kr/co/yeogiga/infrastructure/config/security/SecurityConfig.java
  src/main/java/kr/co/yeogiga/infrastructure/config/security/constant/EndpointConstants.java
  src/main/java/kr/co/yeogiga/presentation/auth/api/AuthApi.java
  src/main/java/kr/co/yeogiga/presentation/auth/controller/AuthController.java
  src/test/java/kr/co/yeogiga/application/auth/service/AuthServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/auth/controller/AuthControllerTest.java
Labels: feat

#24 Feature(IL-54): 업로드 이미지 임시 저장소 저장 로직 구현
  .gitignore
  build.gradle
  src/main/java/kr/co/yeogiga/application/image/dto/ImageUploadRequest.java
  src/main/java/kr/co/yeogiga/application/image/service/ImageProcessingService.java
  src/main/java/kr/co/yeogiga/application/image/service/ImageUploadProcessor.java
  src/main/java/kr/co/yeogiga/application/image/service/TempPlaceImagesCommandService.java
  src/main/java/kr/co/yeogiga/domain/tripplace/entity/TempPlaceImages.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTempPlaceImagesRepository.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTempPlaceImagesRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/TempPlaceImagesRepository.java
  src/main/java/kr/co/yeogiga/domain/tripplace/service/TempPlaceImagesService.java
  src/main/java/kr/co/yeogiga/presentation/image/api/ImageApi.java
  src/main/java/kr/co/yeogiga/presentation/image/controller/ImageController.java
  src/test/java/kr/co/yeogiga/presentation/image/controller/ImageControllerTest.java
Labels: feat

#25 Feature(IL-53): 비밀번호 갱신
  src/main/java/kr/co/yeogiga/application/user/dto/PasswordUpdateReq.java
  src/main/java/kr/co/yeogiga/application/user/service/UserManagementService.java
  src/main/java/kr/co/yeogiga/domain/user/entity/User.java
  src/main/java/kr/co/yeogiga/domain/user/exception/UserErrorType.java
  src/main/java/kr/co/yeogiga/infrastructure/config/security/constant/EndpointConstants.java
  src/main/java/kr/co/yeogiga/presentation/user/api/UserApi.java
  src/main/java/kr/co/yeogiga/presentation/user/controller/UserController.java
  src/test/java/kr/co/yeogiga/application/user/service/UserManagementServiceTest.java
  src/test/java/kr/co/yeogiga/infrastructure/TestSecurityConfig.java
  src/test/java/kr/co/yeogiga/presentation/user/controller/UserControllerTest.java
Labels: feat

#26 Feature(IL-59): 임시 이미지 정렬 로직 구체화
  src/main/java/kr/co/yeogiga/application/image/service/TempImageAssignProcessor.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripPlaceImageService.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripPlaceQueryService.java
  src/main/java/kr/co/yeogiga/domain/tripplace/entity/Place.java
  src/main/java/kr/co/yeogiga/domain/tripplace/entity/TempPlaceImages.java
  src/main/java/kr/co/yeogiga/domain/tripplace/entity/TripDayPlace.java
  src/main/java/kr/co/yeogiga/domain/tripplace/exception/ImageErrorType.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTripDayPlaceRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/TempPlaceImagesRepository.java
  src/main/java/kr/co/yeogiga/domain/tripplace/service/TempPlaceImagesService.java
  src/main/java/kr/co/yeogiga/domain/tripplace/service/TripDayPlaceService.java
  src/main/java/kr/co/yeogiga/presentation/image/api/ImageApi.java
  src/main/java/kr/co/yeogiga/presentation/image/controller/ImageController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripPlaceImageServiceTest.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripPlaceQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/image/controller/ImageControllerTest.java
Labels: feat, refact

#27 Feature(IL-60): 이미지 이동 로직 구현
  src/main/java/kr/co/yeogiga/application/image/service/TempImageAssignProcessor.java
  src/main/java/kr/co/yeogiga/application/tripplace/dto/TripPlaceImageDto.java
  src/main/java/kr/co/yeogiga/application/tripplace/dto/TripPlaceReq.java
  src/main/java/kr/co/yeogiga/application/tripplace/dto/TripPlaceRes.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceCommandService.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceEditingService.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceImageAssignmentService.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceImageMovementService.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceQueryService.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceSavingService.java
  src/main/java/kr/co/yeogiga/domain/trip/exception/TripErrorType.java
  src/main/java/kr/co/yeogiga/domain/tripplace/exception/ImageErrorType.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTripDayPlaceRepository.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTripDayPlaceRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/tripplace/service/TripDayPlaceService.java
  src/main/java/kr/co/yeogiga/presentation/image/api/TripPlaceImageMovementApi.java
  src/main/java/kr/co/yeogiga/presentation/image/controller/TripPlaceImageMovementController.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripPlaceApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripPlaceEditingApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripPlaceController.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripPlaceEditingController.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceCommandServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceEditingServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceImageAssignmentServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceImageMovementServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceQueryServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceSavingServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/image/controller/TripPlaceImageMovementControllerTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripPlaceControllerTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripPlaceEditingControllerTest.java
Labels: feat

#29 Feature(IL-69): 임시 저장된 이미지 삭제 로직 구현
  src/main/java/kr/co/yeogiga/application/image/dto/ImageDeleteDto.java
  src/main/java/kr/co/yeogiga/application/image/dto/ImageUrlDto.java
  src/main/java/kr/co/yeogiga/application/image/service/ImageDeleteProcessor.java
  src/main/java/kr/co/yeogiga/application/image/service/ImageProcessingService.java
  src/main/java/kr/co/yeogiga/application/image/service/TempPlaceImagesCommandService.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTempPlaceImagesRepository.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTempPlaceImagesRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/tripplace/service/TempPlaceImagesService.java
  src/main/java/kr/co/yeogiga/presentation/image/api/ImageApi.java
  src/main/java/kr/co/yeogiga/presentation/image/controller/ImageController.java
  src/test/java/kr/co/yeogiga/application/image/TempPlaceImagesCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/image/controller/ImageControllerTest.java
Labels: feat

#30 Feature(IL-55): 회원 탈퇴
  src/main/java/kr/co/yeogiga/application/auth/dto/SignInDto.java
  src/main/java/kr/co/yeogiga/application/auth/dto/SignUpDto.java
  src/main/java/kr/co/yeogiga/application/auth/service/AuthService.java
  src/main/java/kr/co/yeogiga/application/auth/service/OAuthManagementService.java
  src/main/java/kr/co/yeogiga/application/user/scheduler/UserScheduler.java
  src/main/java/kr/co/yeogiga/application/user/service/UserDeletionProcessor.java
  src/main/java/kr/co/yeogiga/application/user/service/UserManagementService.java
  src/main/java/kr/co/yeogiga/domain/oauth/type/OAuthPlatform.java
  src/main/java/kr/co/yeogiga/domain/user/entity/User.java
  src/main/java/kr/co/yeogiga/domain/user/exception/UserErrorType.java
  src/main/java/kr/co/yeogiga/domain/user/repository/UserRepository.java
  src/main/java/kr/co/yeogiga/domain/user/service/UserService.java
  src/main/java/kr/co/yeogiga/infrastructure/config/SchedulingConfig.java
  src/main/java/kr/co/yeogiga/presentation/user/api/UserApi.java
  src/main/java/kr/co/yeogiga/presentation/user/controller/UserController.java
  src/test/java/kr/co/yeogiga/application/auth/service/AuthServiceTest.java
  src/test/java/kr/co/yeogiga/application/user/service/UserManagementServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/user/controller/UserControllerTest.java
Labels: feat

#31 Feature(IL-70): 매칭된 이미지 삭제 과정 S3 연결
  src/main/java/kr/co/yeogiga/application/tripplace/image/dto/TripPlaceImageDeleteDto.java
  src/main/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageDeleteService.java
  src/test/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageDeleteServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/tripplace/image/controller/TripPlaceImageControllerTest.java
Labels: feat

#32 Feature(IL-87): 아이디, 로그인 중복 여부 확인
  src/main/java/kr/co/yeogiga/application/auth/service/AuthService.java
  src/main/java/kr/co/yeogiga/application/auth/service/OAuthManagementService.java
  src/main/java/kr/co/yeogiga/domain/auth/exception/AuthErrorType.java
  src/main/java/kr/co/yeogiga/domain/user/repository/UserRepository.java
  src/main/java/kr/co/yeogiga/domain/user/service/UserService.java
  src/main/java/kr/co/yeogiga/presentation/auth/api/AuthApi.java
  src/main/java/kr/co/yeogiga/presentation/auth/api/OAuthApi.java
  src/main/java/kr/co/yeogiga/presentation/auth/controller/AuthController.java
  src/test/java/kr/co/yeogiga/application/auth/service/AuthServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/auth/controller/AuthControllerTest.java
Labels: feat

#34 Feature(IL-57): 회원 정보 조회
  src/main/java/kr/co/yeogiga/application/auth/service/AuthService.java
  src/main/java/kr/co/yeogiga/application/auth/service/JwtService.java
  src/main/java/kr/co/yeogiga/application/auth/service/OAuthManagementService.java
  src/main/java/kr/co/yeogiga/application/auth/type/LoginType.java
  src/main/java/kr/co/yeogiga/application/user/dto/UserInfoRes.java
  src/main/java/kr/co/yeogiga/application/user/service/UserManagementService.java
  src/main/java/kr/co/yeogiga/common/jwt/JwtHelper.java
  src/main/java/kr/co/yeogiga/presentation/user/api/UserApi.java
  src/main/java/kr/co/yeogiga/presentation/user/controller/UserController.java
  src/test/java/kr/co/yeogiga/application/auth/service/AuthServiceTest.java
  src/test/java/kr/co/yeogiga/application/user/service/UserManagementServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/user/controller/UserControllerTest.java
Labels: feat

#35 Feature(IL-88): 회원 정보 수정
  src/main/java/kr/co/yeogiga/application/user/dto/UserInfoUpdateReq.java
  src/main/java/kr/co/yeogiga/application/user/service/UserManagementService.java
  src/main/java/kr/co/yeogiga/domain/user/exception/UserErrorType.java
  src/main/java/kr/co/yeogiga/domain/user/repository/UserRepository.java
  src/main/java/kr/co/yeogiga/domain/user/service/UserService.java
  src/main/java/kr/co/yeogiga/presentation/user/api/UserApi.java
  src/main/java/kr/co/yeogiga/presentation/user/controller/UserController.java
  src/test/java/kr/co/yeogiga/application/user/service/UserManagementServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/user/controller/UserControllerTest.java
Labels: feat

#36 Feature(IL-77): 이미지 및 여행 일차 요약 정보 조회 로직 구현
  src/main/java/kr/co/yeogiga/application/tripplace/dto/TripDaySummaryRes.java
  src/main/java/kr/co/yeogiga/application/tripplace/dto/TripPlaceRes.java
  src/main/java/kr/co/yeogiga/application/tripplace/image/dto/TripPlaceImageReq.java
  src/main/java/kr/co/yeogiga/application/tripplace/image/dto/TripPlaceImageRes.java
  src/main/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageMovementService.java
  src/main/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageQueryService.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceQueryService.java
  src/main/java/kr/co/yeogiga/domain/tripplace/entity/Place.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTripDayPlaceRepository.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTripDayPlaceRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/tripplace/service/TripDayPlaceService.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/api/TripPlaceApi.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/controller/TripPlaceController.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/image/api/TripPlaceImageApi.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/image/controller/TripPlaceImageController.java
  src/test/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageMovementServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageQueryServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/tripplace/controller/TripPlaceControllerTest.java
  src/test/java/kr/co/yeogiga/presentation/tripplace/image/controller/TripPlaceImageControllerTest.java
Labels: feat

#38 Feature(IL-96): JWT 클레임 내 아이디 제거
  src/main/java/kr/co/yeogiga/application/auth/service/AuthService.java
  src/main/java/kr/co/yeogiga/application/auth/service/JwtService.java
  src/main/java/kr/co/yeogiga/application/auth/service/OAuthManagementService.java
  src/main/java/kr/co/yeogiga/common/jwt/JwtHelper.java
  src/main/java/kr/co/yeogiga/common/jwt/dto/JwtClaims.java
  src/test/java/kr/co/yeogiga/application/auth/service/AuthServiceTest.java
Labels: feat

#39 Feature(IL-97): 임시 저장된 이미지 조회 로직 구현
  src/main/java/kr/co/yeogiga/application/image/dto/TempImageDto.java
  src/main/java/kr/co/yeogiga/application/image/service/TempPlaceImagesQueryService.java
  src/main/java/kr/co/yeogiga/presentation/image/api/ImageApi.java
  src/main/java/kr/co/yeogiga/presentation/image/controller/ImageController.java
  src/test/java/kr/co/yeogiga/application/image/TempPlaceImagesQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/image/controller/ImageControllerTest.java
Labels: feat

#40 Docs: Swagger 문서화 정보 추가 작성
  src/main/java/kr/co/yeogiga/application/tripplace/image/dto/TripPlaceImageDeleteDto.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/api/TripPlaceApi.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/api/TripPlaceEditingApi.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/image/api/TripPlaceImageApi.java
Labels: docs

#41 Feature(IL-99): 매칭된 이미지 재정렬 로직 구현
  src/main/java/kr/co/yeogiga/application/image/service/TempImageAssignProcessor.java
  src/main/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageAssignmentService.java
  src/main/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageReassignmentService.java
  src/main/java/kr/co/yeogiga/domain/tripplace/entity/Place.java
  src/main/java/kr/co/yeogiga/domain/tripplace/entity/TripDayPlace.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/image/api/TripPlaceImageApi.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/image/controller/TripPlaceImageController.java
  src/test/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageAssignmentServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceImageReassignmentServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/tripplace/image/controller/TripPlaceImageControllerTest.java
Labels: feat

#44 Fix: User 엔티티 내 이메일 값 NOT NULL 제약 해제
  src/main/java/kr/co/yeogiga/domain/user/entity/User.java
Labels: fix

#43 Feature(IL-106): 여행 방장 루트 저장 로직 구현
  src/main/java/kr/co/yeogiga/application/route/dto/RouteReq.java
  src/main/java/kr/co/yeogiga/application/route/service/TripLeaderCommandService.java
  src/main/java/kr/co/yeogiga/infrastructure/redis/RedisRepository.java
  src/main/java/kr/co/yeogiga/infrastructure/redis/constant/RouteConstant.java
  src/main/java/kr/co/yeogiga/presentation/route/api/RouteApi.java
  src/main/java/kr/co/yeogiga/presentation/route/controller/RouteController.java
  src/test/java/kr/co/yeogiga/application/route/service/TripLeaderCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/route/controller/RouteControllerTest.java
Labels: feat

#42 Feature(IL-104): 여행 생성
  src/main/java/kr/co/yeogiga/application/trip/dto/TripReq.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripCommandService.java
  src/main/java/kr/co/yeogiga/domain/trip/entity/Trip.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/TripMemberRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/TripRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripMemberService.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripService.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripControllerTest.java
Labels: feat

#45 Feature(IL-107): Redis에 저장된 여행 루트 RDB 로드 로직 구현
  src/main/java/kr/co/yeogiga/application/route/scheduler/RouteScheduler.java
  src/main/java/kr/co/yeogiga/application/route/service/TripLeaderCommandService.java
  src/main/java/kr/co/yeogiga/domain/triproute/converter/RouteListConverter.java
  src/main/java/kr/co/yeogiga/domain/triproute/entity/Route.java
  src/main/java/kr/co/yeogiga/domain/triproute/entity/TripRoute.java
  src/main/java/kr/co/yeogiga/domain/triproute/repository/CustomTripRouteRepository.java
  src/main/java/kr/co/yeogiga/domain/triproute/repository/CustomTripRouteRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/triproute/repository/TripRouteRepository.java
  src/main/java/kr/co/yeogiga/domain/triproute/service/TripRouteService.java
  src/main/java/kr/co/yeogiga/infrastructure/redis/RedisRepository.java
  src/main/java/kr/co/yeogiga/infrastructure/redis/constant/RouteConstant.java
  src/main/resources/application-common.yml
  src/test/java/kr/co/yeogiga/domain/user/repository/UserRepositoryTest.java
  src/test/java/kr/co/yeogiga/infrastructure/TestObjectMapperConfig.java
Labels: feat

#46 Feature(IL-114): 여행 시간 수정
  src/main/java/kr/co/yeogiga/application/trip/dto/TripReq.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripCommandService.java
  src/main/java/kr/co/yeogiga/domain/trip/entity/Trip.java
  src/main/java/kr/co/yeogiga/domain/trip/exception/TripErrorType.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripService.java
  src/main/java/kr/co/yeogiga/domain/trip/type/TravelStatus.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripControllerTest.java
Labels: feat

#47 Feature(IL-116): 여행 상태 갱신 스케줄링
  src/main/java/kr/co/yeogiga/application/trip/scheduler/TripScheduler.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripCommandService.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/TripRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripService.java
Labels: feat

#48 Feature(IL-113): 이미지 매핑 과정 중, 시간데이터를 통한 이동 경로의 GPS 매핑 로직 추가
  src/main/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageAssignmentService.java
  src/main/java/kr/co/yeogiga/domain/tripplace/entity/Image.java
  src/main/java/kr/co/yeogiga/domain/triproute/repository/TripRouteRepository.java
  src/main/java/kr/co/yeogiga/domain/triproute/service/TripRouteService.java
  src/test/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageAssignmentServiceTest.java
Labels: feat

#49 Feature(IL-119): 여행 멤버 참가
  src/main/java/kr/co/yeogiga/application/trip/service/TripMemberCommandService.java
  src/main/java/kr/co/yeogiga/domain/trip/exception/TripMemberErrorType.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/TripMemberRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripMemberService.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripMemberApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripMemberController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripMemberCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripMemberControllerTest.java
Labels: feat

#50 Feature(IL-115): 여행 이동 경로 조회 로직 구현
  src/main/java/kr/co/yeogiga/application/route/dto/RouteRes.java
  src/main/java/kr/co/yeogiga/application/route/service/TripLeaderCommandService.java
  src/main/java/kr/co/yeogiga/application/route/service/TripRouteQueryService.java
  src/main/java/kr/co/yeogiga/domain/triproute/repository/TripRouteRepository.java
  src/main/java/kr/co/yeogiga/domain/triproute/service/TripRouteService.java
  src/main/java/kr/co/yeogiga/presentation/route/api/RouteApi.java
  src/main/java/kr/co/yeogiga/presentation/route/controller/RouteController.java
  src/test/java/kr/co/yeogiga/application/route/service/TripRouteQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/route/controller/RouteControllerTest.java
Labels: feat

#51 Feature(IL-122): W2M 쓰기 연산 로직 구현
  src/main/java/kr/co/yeogiga/application/calendar/dto/CalendarReq.java
  src/main/java/kr/co/yeogiga/application/calendar/service/CalendarCommandService.java
  src/main/java/kr/co/yeogiga/domain/calendar/converter/LocalDateListConverter.java
  src/main/java/kr/co/yeogiga/domain/calendar/entity/Calendar.java
  src/main/java/kr/co/yeogiga/domain/calendar/repository/CalendarRepository.java
  src/main/java/kr/co/yeogiga/domain/calendar/service/CalendarService.java
  src/main/java/kr/co/yeogiga/domain/trip/exception/TripErrorType.java
  src/main/java/kr/co/yeogiga/presentation/calendar/api/CalendarApi.java
  src/main/java/kr/co/yeogiga/presentation/calendar/controller/CalendarController.java
  src/test/java/kr/co/yeogiga/application/calendar/service/CalendarCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/calendar/controller/CalendarControllerTest.java
Labels: feat

#53 Feature(IL-123): W2M 조회 연산 로직 구현
  src/main/java/kr/co/yeogiga/application/calendar/dto/CalendarRes.java
  src/main/java/kr/co/yeogiga/application/calendar/service/CalendarQueryService.java
  src/main/java/kr/co/yeogiga/domain/calendar/repository/CalendarRepository.java
  src/main/java/kr/co/yeogiga/domain/calendar/service/CalendarService.java
  src/main/java/kr/co/yeogiga/presentation/calendar/api/CalendarApi.java
  src/main/java/kr/co/yeogiga/presentation/calendar/controller/CalendarController.java
  src/test/java/kr/co/yeogiga/application/calendar/service/CalendarQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/calendar/controller/CalendarControllerTest.java
Labels: feat

#54 Feature(IL-125): 목적지 방문 여부 로직 구현
  src/main/java/kr/co/yeogiga/application/tripplace/dto/TripPlaceRes.java
  src/main/java/kr/co/yeogiga/application/tripplace/dto/VisitedMarkReq.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceCommandService.java
  src/main/java/kr/co/yeogiga/domain/tripplace/entity/Place.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTripDayPlaceRepository.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTripDayPlaceRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/tripplace/service/TripDayPlaceService.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/api/TripPlaceApi.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/controller/TripPlaceController.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/tripplace/controller/TripPlaceControllerTest.java
Labels: feat, refact

#55 Feature(IL-126): 이미지 즐겨찾기 로직 구현
  src/main/java/kr/co/yeogiga/application/tripplace/image/dto/FavoriteImageReq.java
  src/main/java/kr/co/yeogiga/application/tripplace/image/dto/FavoriteImageRes.java
  src/main/java/kr/co/yeogiga/application/tripplace/image/dto/TripPlaceImageRes.java
  src/main/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageCommandService.java
  src/main/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageQueryService.java
  src/main/java/kr/co/yeogiga/domain/tripplace/entity/Image.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTripDayPlaceRepository.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTripDayPlaceRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/tripplace/service/TripDayPlaceService.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/image/api/TripPlaceImageApi.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/image/controller/TripPlaceImageController.java
  src/test/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageCommandServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/tripplace/image/controller/TripPlaceImageControllerTest.java
Labels: feat

#56 Feature(IL-124): 사용자가 속한 여행 조회
  src/main/java/kr/co/yeogiga/application/trip/dto/TripRes.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripQueryService.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/TripMemberRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripMemberService.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripControllerTest.java
Labels: feat

#57 Feature(IL-127): 메인 화면 내 여행 조회
  src/main/java/kr/co/yeogiga/application/trip/dto/TripRes.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripQueryService.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTripDayPlaceRepository.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTripDayPlaceRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/tripplace/service/TripDayPlaceService.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripControllerTest.java
Labels: feat

#59 Feature(IL-135): 여행 멤버 조회
  src/main/java/kr/co/yeogiga/application/trip/dto/TripMemberRes.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripMemberQueryService.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/TripMemberRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripMemberService.java
  src/main/java/kr/co/yeogiga/domain/user/entity/User.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripMemberApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripMemberController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripMemberQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripMemberControllerTest.java
Labels: feat

#60 Feature(IL-137): 여행 삭제
  src/main/java/kr/co/yeogiga/application/trip/service/TripCommandService.java
  src/main/java/kr/co/yeogiga/domain/trip/entity/Trip.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripService.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripControllerTest.java
Labels: feat

#62 Feature: 여행 조회 반환값 변경
  src/main/java/kr/co/yeogiga/application/trip/dto/TripRes.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripCommandService.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripQueryService.java
  src/main/java/kr/co/yeogiga/common/response/success/SuccessResponse.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripService.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripCommandServiceTest.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripControllerTest.java
Labels: feat

#63 Feature(IL-139): 특정 여행 조회
  src/main/java/kr/co/yeogiga/application/trip/dto/TripRes.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripQueryService.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripControllerTest.java
Labels: feat

#64 Fix: OAuth 로그인 시 사용자 엔티티 조회 에러 수정
  src/main/java/kr/co/yeogiga/domain/user/repository/UserRepository.java
Labels: fix

#65 Fix: 트랜잭션 옵션 수정 및 여행 응답 DTO 변경
  src/main/java/kr/co/yeogiga/application/trip/dto/TripReq.java
  src/main/java/kr/co/yeogiga/application/trip/dto/TripRes.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripCommandService.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripQueryService.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripApi.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripControllerTest.java
Labels: fix, feat

#67 Feature(IL-145): 여행 탈퇴
  src/main/java/kr/co/yeogiga/application/trip/service/TripMemberCommandService.java
  src/main/java/kr/co/yeogiga/domain/trip/exception/TripMemberErrorType.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/TripMemberRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/TripRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripMemberService.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripService.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripMemberApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripMemberController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripMemberCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripMemberControllerTest.java
Labels: feat

#68 Feature(IL-146): 여행 멤버 추방
  src/main/java/kr/co/yeogiga/application/trip/service/TripMemberCommandService.java
  src/main/java/kr/co/yeogiga/domain/trip/exception/TripMemberErrorType.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripService.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripMemberApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripMemberController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripMemberCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripMemberControllerTest.java
Labels: feat

#69 Feature(IL-156): 집결지 핀 생성
  src/main/java/kr/co/yeogiga/application/pin/dto/PinReq.java
  src/main/java/kr/co/yeogiga/application/pin/service/PinCommandService.java
  src/main/java/kr/co/yeogiga/domain/pin/entity/Pin.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripService.java
  src/main/java/kr/co/yeogiga/infrastructure/redis/constant/PinConstant.java
  src/main/java/kr/co/yeogiga/presentation/pin/controller/PinController.java
  src/main/java/kr/co/yeogiga/presentation/pin/controller/api/PinApi.java
  src/test/java/kr/co/yeogiga/application/pin/service/PinCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/pin/controller/PinControllerTest.java
Labels: feat

#72 Feature(IL-153): Silent Push 전송 로직 구현
  .github/workflows/cd.yml
  .gitignore
  build.gradle
  src/main/java/kr/co/yeogiga/application/fcm/scheduler/FcmScheduler.java
  src/main/java/kr/co/yeogiga/application/fcm/service/TripPushSender.java
  src/main/java/kr/co/yeogiga/application/fcm/service/TripTokenPushProcessor.java
  src/main/java/kr/co/yeogiga/application/user/service/UserFcmTokenService.java
  src/main/java/kr/co/yeogiga/domain/user/entity/User.java
  src/main/java/kr/co/yeogiga/domain/user/repository/UserRepository.java
  src/main/java/kr/co/yeogiga/domain/user/service/UserService.java
  src/main/java/kr/co/yeogiga/infrastructure/config/FcmConfig.java
  src/main/java/kr/co/yeogiga/infrastructure/fcm/FcmNotificationSender.java
  src/main/java/kr/co/yeogiga/infrastructure/fcm/response/FcmSendResult.java
  src/main/java/kr/co/yeogiga/infrastructure/redis/constant/TripMemberTokenConstant.java
  src/main/resources/application.yml
  src/test/java/kr/co/yeogiga/application/user/service/UserFcmTokenServiceTest.java
Labels: feat

#75 Refactor: 목적지 순서 변경 및 삽입 로직 변경
  src/main/java/kr/co/yeogiga/application/tripplace/dto/TripPlaceReq.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceCommandService.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceEditingService.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTripDayPlaceRepository.java
  src/main/java/kr/co/yeogiga/domain/tripplace/repository/CustomTripDayPlaceRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/tripplace/service/TripDayPlaceService.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/api/TripPlaceEditingApi.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/controller/TripPlaceEditingController.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceCommandServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceEditingServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/tripplace/controller/TripPlaceControllerTest.java
  src/test/java/kr/co/yeogiga/presentation/tripplace/controller/TripPlaceEditingControllerTest.java
Labels: refact

#74 Feature(IL-167): 목적지 순서 추천 알고리즘 구현
  src/main/java/kr/co/yeogiga/application/tripplace/image/service/TripPlaceImageAssignmentService.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceSortService.java
  src/main/java/kr/co/yeogiga/common/util/DistanceUtils.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/api/TripPlaceEditingApi.java
  src/main/java/kr/co/yeogiga/presentation/tripplace/controller/TripPlaceEditingController.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceSortServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/tripplace/controller/TripPlaceEditingControllerTest.java
Labels: feat

#73 Feature(IL-165): 준비 중 여행 조회
  src/main/java/kr/co/yeogiga/application/trip/dto/TripRes.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripQueryService.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/TripMemberRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripMemberService.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripQueryServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripControllerTest.java
Labels: feat

#76 Feature(IL-155): 사용자 프로필 업로드
  src/main/java/kr/co/yeogiga/application/image/dto/ImageUploadRequest.java
  src/main/java/kr/co/yeogiga/application/image/service/ImageProcessingService.java
  src/main/java/kr/co/yeogiga/application/image/service/ImageUploadProcessor.java
  src/main/java/kr/co/yeogiga/domain/tripplace/exception/ImageErrorType.java
  src/main/java/kr/co/yeogiga/domain/user/entity/User.java
  src/main/java/kr/co/yeogiga/infrastructure/s3/AwsS3Storage.java
  src/main/java/kr/co/yeogiga/presentation/user/api/UserApi.java
  src/main/java/kr/co/yeogiga/presentation/user/controller/UserController.java
  src/test/java/kr/co/yeogiga/presentation/user/controller/UserControllerTest.java
Labels: feat, refact

#78 Feature(IL-158): 여행 상태 변경 과정 중, FCM Token 저장 로직 구현
  .gitignore
  build.gradle
  src/main/java/kr/co/yeogiga/application/trip/scheduler/TripScheduler.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripCommandService.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceEditingService.java
  src/main/java/kr/co/yeogiga/application/tripplace/service/TripPlaceSortService.java
  src/main/java/kr/co/yeogiga/domain/trip/dto/TripFcmTokenQueryDto.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/CustomTripRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/CustomTripRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/TripRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripService.java
  src/main/java/kr/co/yeogiga/infrastructure/config/QueryDslConfig.java
  src/main/java/kr/co/yeogiga/infrastructure/redis/RedisRepository.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripCommandServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceEditingServiceTest.java
  src/test/java/kr/co/yeogiga/application/tripplace/service/TripPlaceSortServiceTest.java
  src/test/java/kr/co/yeogiga/domain/user/repository/UserRepositoryTest.java
Labels: feat, chore

#79 Feature(IL-160): 시작된 여행의 멤버에게 Notification Push 전송 로직 구현
  src/main/java/kr/co/yeogiga/application/fcm/constant/FcmConstant.java
  src/main/java/kr/co/yeogiga/application/fcm/service/TripPushSender.java
  src/main/java/kr/co/yeogiga/application/fcm/service/TripTokenPushProcessor.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripCommandService.java
  src/main/java/kr/co/yeogiga/domain/trip/dto/TripFcmTokenQueryDto.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/CustomTripRepositoryImpl.java
  src/main/java/kr/co/yeogiga/infrastructure/fcm/FcmNotificationSender.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripCommandServiceTest.java
Labels: feat

#80 Feature(IL-161): 여행 멤버 위치 저장
  build.gradle
  src/main/java/kr/co/yeogiga/application/trip/dto/TripMemberLocationDto.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripMemberLocationCommandService.java
  src/main/java/kr/co/yeogiga/infrastructure/redis/RedisRepository.java
  src/main/java/kr/co/yeogiga/infrastructure/redis/constant/TripMemberLocationConstant.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripMemberLocationApi.java
  src/main/java/kr/co/yeogiga/presentation/trip/controller/TripMemberLocationController.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripMemberLocationCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripMemberLocationControllerTest.java
Labels: feat, chore
