Repository Team-Ilmansa/yeogiga-was, pull requests merged in 2025-06, with the labels that each got.

#82 Feature(IL-170): 집결지 요청 후 푸시 알림 적용
  src/main/java/kr/co/yeogiga/application/fcm/constant/FcmConstant.java
  src/main/java/kr/co/yeogiga/application/fcm/service/TripPushSender.java
  src/main/java/kr/co/yeogiga/application/pin/service/PinCommandService.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripCommandService.java
  src/main/java/kr/co/yeogiga/common/response/error/type/CommonErrorType.java
  src/main/java/kr/co/yeogiga/domain/trip/dto/TripFcmTokenInfoDto.java
  src/main/java/kr/co/yeogiga/domain/trip/entity/Trip.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/CustomTripRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/CustomTripRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/trip/service/TripService.java
  src/main/java/kr/co/yeogiga/presentation/pin/api/PinApi.java
  src/main/java/kr/co/yeogiga/presentation/pin/controller/PinController.java
  src/test/java/kr/co/yeogiga/application/pin/service/PinCommandServiceTest.java
Labels: feat

#83 Refactor: TripRepository QueryDsl 마이그레이션
  src/main/java/kr/co/yeogiga/domain/trip/repository/CustomTripRepository.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/CustomTripRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/trip/repository/TripRepository.java
  src/main/java/kr/co/yeogiga/domain/user/repository/UserRepository.java
  src/main/java/kr/co/yeogiga/domain/user/service/UserService.java
Labels: refact

#85 Refactor: UserRepository QueryDsl 마이그레이션
  build.gradle
  src/main/java/kr/co/yeogiga/domain/user/repository/CustomUserRepository.java
  src/main/java/kr/co/yeogiga/domain/user/repository/CustomUserRepositoryImpl.java
  src/main/java/kr/co/yeogiga/domain/user/repository/UserRepository.java
  src/main/java/kr/co/yeogiga/domain/user/service/UserService.java
  src/main/java/kr/co/yeogiga/infrastructure/config/QueryDslConfig.java
Labels: chore, refact

#86 Refactor: GPS 저장 로직 수정 및 여행 시간 수정 유효성 검사 추가
  src/main/java/kr/co/yeogiga/application/route/dto/RouteDto.java
  src/main/java/kr/co/yeogiga/application/route/dto/RouteReq.java
  src/main/java/kr/co/yeogiga/application/route/service/TripLeaderCommandService.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripCommandService.java
  src/main/java/kr/co/yeogiga/application/trip/service/TripMemberLocationCommandService.java
  src/main/java/kr/co/yeogiga/common/util/DateTimeUtils.java
  src/main/java/kr/co/yeogiga/domain/trip/exception/TripErrorType.java
  src/main/java/kr/co/yeogiga/infrastructure/redis/RedisRepository.java
  src/main/java/kr/co/yeogiga/presentation/route/api/RouteApi.java
  src/main/java/kr/co/yeogiga/presentation/route/controller/RouteController.java
  src/main/java/kr/co/yeogiga/presentation/trip/api/TripApi.java
  src/test/java/kr/co/yeogiga/application/route/service/TripLeaderCommandServiceTest.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripCommandServiceTest.java
  src/test/java/kr/co/yeogiga/application/trip/service/TripMemberLocationCommandServiceTest.java
  src/test/java/kr/co/yeogiga/presentation/route/controller/RouteControllerTest.java
  src/test/java/kr/co/yeogiga/presentation/trip/controller/TripControllerTest.java
Labels: refact
